/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  important: true,
  theme: {
    screens: {
      'xxs': '280px',
      'x.5s':'400px',
      'xs':'500px',
      'sm': '640px',
      'md': '768px',
      'lg': '1024px',
      'xl': '1280px',
      '2xl':'1536px'
    },
    maxWidth:{
      '1/2': '50%',
      '2/3': '66.66666%',
      'full': '100%',
      '40': '40%',
      "30": '30rem',
      "40r": '40rem',
      '1/3':'33.3333%',
      '3/4': '75%',
      '1/4': '25%',
      '32%': '32%',
      '5.5/12': '46%',
      "3.7/12": '30%',
      '22%': '23%',
      'auto':'auto',
    },
    minWidth: {
      "30": '30rem',
      '8':'2rem',
      '56': '14rem',
      '32':'8rem',
    },
    extend: {
      backgroundImage: {
        'portfolio01':"url('/src/constants/portfolio_01.jpg')",
        'portfolio02':"url('/src/constants/portfolio_02.jpg')",
        'portfolio03':"url('/src/constants/portfolio_03.jpg')",
        'portfolio04':"url('/src/constants/portfolio_04.jpg')",
        'portfolio05':"url('/src/constants/portfolio_05.jpg')",
        'portfolio06':"url('/src/constants/portfolio_06.jpg')",
        'faqCard':"url('/src/constants/faq-card-background.jpg')",
        'services':"url('/src/constants/counters_bg.jpg')",
        'offer_card':"url('/src/constants/faq-card-background.jpg')",
        'landing':"url('/src/constants/nimbus_page_title.jpg')",
        'pricing_price':"url('/src/constants/prising-table_01.jpg')",
        'pricing_price2':"url('/src/constants/prising-table_02.jpg')",
        'revolution_rightside':"url('/src/constants/services_01.jpg')",
        'track_bg':"url('/src/constants/footer_bg.jpg')",
        'stages_background':"url('/src/constants/icon-box.jpg')",
      },
    },
    colors: {
      darkYellow: '#ffae00',
      lightYellow: '#ffc13e',
      lightDark: '#212121',
      dark:'#191919',
      white: '#fff',
      dribbble: '#ea4c89',
      behance: '#1769ff',
      black: '#000',
      bbb: '#bbb',
      e69: '#e69d00',
      999: "#999",
      c6: '#c6c6c6',
      f7: '#f7f7f7',
      section: '#f8f8f8',
      61: '#616161',
      golden: '#f9d322',
      danger: '#ff144b',
      borders:'#e5e5e5',
    }    
  },
  plugins: [],
}