import { images } from "../../constants"
export const clothes = [
    {
        image: images.shop_011,
        title: 'Sweatshirt Motif',
        rate: 5,
        price: 17.99,
        sale: false,
        oPrice:19.99,
        cat: 'Sweatshirt',
        id: 1,
        image80:images.shop011x80
    },
    {
        image: images.shop_021,
        title: 'Sweatshirt Gray',
        rate: 4,
        price: 9.99,
        sale: false,
        oPrice:19.99,
        cat:'Sweatshirt',
        id: 2,
        image80:images.shop012x80
    },
    {
        image: images.shop_031,
        title: 'Hooded Sweatshirt',
        rate: 4.5,
        price: 19.99,
        sale: true,
        oPrice:21.99,
        cat:'Hooded',
        id: 3,
        image80:images.shop013x80,
    },
    {
        image: images.shop_041,
        title: 'Sweatshirt Pink',
        rate: 4,
        price: 9.99,
        sale: true,
        oPrice:12.99,
        cat: 'Sweatshirt',
        id: 4,
        image80:images.shop014x80
    },
    {
        image: images.shop_051,
        title: 'Sweatshirt Cotton',
        rate: 4.5,
        price: 15.99,
        sale: false,
        oPrice:12.99,
        cat:'Backpack',
        id: 5,
        image80:images.shop015x80,
    },
    {
        image: images.shop_061,
        title: 'Short Sweatshirt',
        rate: 5,
        price: 24.99,
        sale: false,
        oPrice:12.99,
        cat:'Sweatshirt',
        id: 6,
        image80:images.shop016x80,
    },
    {
        image: images.shop_071,
        title: 'Hooded Shirt',
        rate: 4.5,
        price: 12.99,
        sale: false,
        oPrice:12.99,
        cat:'Hooded',
        id: 7,
        image80:images.shop017x80,
    },
    {
        image: images.shop_081,
        title: 'Lightweight Hooded',
        rate: 5,
        price: 17.99,
        sale: true,
        oPrice:23.99,
        cat:'Shoes',
        id: 8,
        image80:images.shop018x80,
    },
    {
        image: images.shop_091,
        title: 'Hooded Shirt',
        rate: 4.5,
        price: 14.99,
        sale: false,
        oPrice:23.99,
        cat:'Accessories',
        id: 9,
        image80:images.shop019x80,
    },
    {
        image: images.shop_101,
        title: 'Pink Sweatshirt',
        rate: 4,
        price: 19.99,
        sale: false,
        oPrice:23.99,
        cat:'Sweatshirt',
        id: 10,
        image80:images.shop010x80,
    },
    {
        image: images.shop_111,
        title: 'Sweatshirt Short',
        rate: 5,
        price: 17.99,
        sale: true,
        oPrice:23.99,
        cat:'Backpack',
        id: 11,
        image80:images.shop111x80,
    },
    {
        image: images.shop_121,
        title: 'Hooded Sweatshirt',
        rate: 4.5,
        price: 19.99,
        sale: false,
        oPrice:23.99,
        cat:'Hooded',
        id: 12,
        image80:images.shop112x80,
    },
]
export const cati = [
    '',
    'Accessories',
    'Backpack',
    'Hooded',
    'Shoes',
    'Sweatshirt',
]
export const tags = [
    'art',
    'clothes',
    'creative',
    'ux',
    'design',
    'inspiration',
    'motion',
]
// const nb = 
export const tableColumns = [
    'Product',
    '\u00A0',
    'Price',
    'Quantity',
    'Total',
    '\u00A0',
]